eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    #instance-id: 192.168.1.103:8080
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: client
      #cloud:
      #client:
    #ipAddress: 192.168.1.103
server:
  port: 8080